Make bin/git_start a bit more robust

diff --git a/bin/git_start b/bin/git_start
--- a/bin/git_start
+++ b/bin/git_start
@@ -1,11 +1,24 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
-if [ $# -ne 2 ]; then
-    echo "usage: $0 NEW_BRANCH_NAME"
-    exit 127
+if [ $# -ne 1 ]; then
+  echo "usage: $0 NEW_BRANCH_NAME" >&2
+  exit 127
 fi
-branch_name=$1
-git checkout master || exit 1
-git pull origin master || exit 1
-git branch $branch_name || exit 1
-git checkout $branch_name || exit 1
+
+function die() {
+  local __msg="${1:-Unexpected error; aborting.}"
+  echo -e "${__msg} (${BASH_SOURCE[1]}:${FUNCNAME[1]} line ${BASH_LINENO[0]})"
+  exit 1
+}
+
+branch=$(git branch | grep '^\*' | awk '{print $2}')
+if [ "$branch" != "master" ]; then
+  git checkout master
+fi
+exit 0
+
+git pull || die "Could not sync master"
+git branch $1 || die "Could not cut new branch $1"
+git checkout $1 || die "Could not switch to new branch $1"
+
+
